development:
  adapter: postgresql
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['PUMA_MAX_THREADS'] || 5 %>
  timeout: 5000

test:
  adapter: postgresql
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['PUMA_MAX_THREADS'] || 5 %>
  timeout: 5000

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['PUMA_MAX_THREADS'] || 5 %>
  timeout: 5000