<%= Rails.env %>:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  solo_code: <%= ENV['SOLO_CODE'] %>
  couple_code: <%= ENV['COUPLE_CODE'] %>
  family_code: <%= ENV['FAMILY_CODE'] %>